\c stonewall_db;

INSERT INTO resources
    (title, link, category)
VALUES
    ('An LGBTQ History Educators’ Guide', 'https://www.academia.edu/36806202/An_LGBTQ_History_Educators_Guide', 0),
    ('Teaching Tolerance’s New LGBTQ Best Practices Guide', 'https://www.tolerance.org/magazine/fall-2018/tts-new-lgbtq-best-practices-guide', 0),
    ('Teaching Tolerance’s Learning Plan: Gender and Sexuality', 'https://www.tolerance.org/learning-plan/gender-and-sexuality-the-purpose-is-to-get-students-thinking-about-social-justice', 0),
    ('Teaching Tolerance’s Learning Plan: Gender Identity and Sexuality', 'https://www.tolerance.org/learning-plan/gender-identity-and-sexuality', 0),
    ('Educator Guides for GLSEN Programs', 'https://www.glsen.org/educate/resources/guides', 0),
    ('LGBT-Inclusive Curriculum', 'https://www.glsen.org/educate/resources/curriculum', 0),
    ('Critical Media Literacy’s LGBTQ education resources', 'http://criticalmediaproject.org/category/lgbtq/', 0),
    ('California’s FAIR Ed Act includes lesson plans', 'http://www.faireducationact.com/about-fair/', 0),
    ('The Gender Unicorn', 'http://www.transstudent.org/gender/', 1),
    ('Genderbread Person', 'https://www.genderbread.org/', 1),
    ('Gender Inclusive Language', 'https://www.teenvogue.com/story/how-to-use-gender-neutral-words', 1),
    ('Gender Spectrum Story Time', 'https://www.youtube.com/watch?v=3rx0q0M61uE&feature=youtu.be', 1),
    ('Human Rights Campaign: Guide to Supporting Transgender Students in K-12 Schools', 'https://assets2.hrc.org/files/assets/resources/Schools-In-Transition.pdf?_ga=2.81582547.559796857.1539701294-715597900.1539701294', 1),
    ('Teaching Tolerance’s Learning Plan: Gender Stereotypes and Gender Identity', 'https://www.tolerance.org/learning-plan/gender-stereotypes-and-gender-identity', 1),
    ('History Channel: How the Stonewall Riots Sparked a Movement', 'https://www.youtube.com/watch?v=Q9wdMJmuBlA', 2),
    ('Laverne Cox, Candis Cayne & More on Marsha P. Johnson and Sylvia Rivera', 'https://www.youtube.com/watch?v=C-pMeR2lnlo', 2),
    ('PBS American Experience: Stonewall Uprising', 'https://www.pbs.org/video/american-experience-stonewall-uprising/', 2),
    ('PBS American Experience: Legacy of the Stonewall Riots', 'https://www.pbs.org/video/american-experience-legacy-stonewall-riots/', 2),
    ('Stonewall Project Website', 'https://www.nps.gov/ston/index.htm', 2),
    ('Making Gay History/History UnErased LGBT-inclusive 8th and 11th Grade Guides', 'https://makinggayhistory.org/classroom/', 2),
    ('Making History (original 1992 edition of Making Gay History) by Eric Marcus', 'https://www.barnesandnoble.com/w/making-history-eric-marcus/1121788836?ean=9780062848260', 2),
    ('Stonewall picture book for children', 'https://www.penguinrandomhouse.com/books/538691/pride-the-story-of-harvey-milk-and-the-rainbow-flag-by-rob-sanders-illustrated-by-steven-salerno/9780399555312/', 2),
    ('PBS American Experience Stonewall Uprising documentary', 'https://www.pbs.org/wgbh/americanexperience/films/stonewall/', 2),
    ('David Isay/StoryCorps Stonewall Audio Documentary, 1989', 'https://storycorps.org/listen/remembering-stonewall/', 2),
    ('LGBTQ Heritage', 'https://www.nps.gov/subjects/tellingallamericansstories/lgbtqheritage.htm', 2),
    ('Lesbian Herstory Archives', 'http://www.lesbianherstoryarchives.org/', 3),
    ('LGBT Community Center National History Archive', 'https://gaycenter.org/archives/', 3),
    ('NYC LGBTQ Historical Sites', 'https://www.nyclgbtsites.org/', 3),
    ('Digital Transgender Archive', 'https://www.digitaltransgenderarchive.net/', 3),
    ('Library of Congress’s LGBTQ+ Studies Research Guide', 'https://www.loc.gov/rr/main/lgbtq/lgbtqgeneralguide/index.html', 3),
    ('LGBT Issues in Records at the National Archives', 'https://www.archives.gov/research/lgbt', 3),
    ('50 Zines by Queer People of Color', 'https://www.autostraddle.com/50-zines-by-queer-people-of-color-184692/', 4),
    ('QZAP-Zine Archive', 'https://www.autostraddle.com/50-zines-by-queer-people-of-color-184692/', 4),
    ('7 Awesome Zines On LGBTQ Identities That You Can Read Online!', 'https://www.youthkiawaaz.com/2016/07/must-read-lgbtq-zines/', 4),
    ('Texas Queer Youth Zine', 'https://texasqueeryouthzine.weebly.com/', 4),
    ('Reflecting a Revolutionary Time: ‘Zines by Queer Street Youth in the 1960s', 'https://www.digitaltransgenderarchive.net/news/2016-04-reflecting-a-revolutionary-time-zines-by-queer-street-youth-in-the-1960s', 4);